MAD-33 Added localization support
abodsakah/BTH-appen pull request #8
Opened 2022-11-08 08:45 UTC by abodsakah

The whole is easily translatable now by just pulling a google sheets document with the strings and their respective translation.

2022-11-08 09:00 UTC, NoahHakansson requested changes
Varför finns det både en CSV och JSON file. En JSON bör räcka?

2022-11-08 09:00 UTC, NoahHakansson commented on app/src/Views/Login.js
> +					<Text style={styles.forgotPassword}>{t('problemes_with_login')}</Text>
```suggestion
					<Text style={styles.forgotPassword}>{t('can_not_login')}</Text>
```

2022-11-08 16:51 UTC, abodsakah commented
> Varför finns det både en CSV och JSON file. En JSON bör räcka?

Nu är den borta

2022-11-09 09:11 UTC, NoahHakansson commented on app/src/locale/translation.json
> +        "sv-sv": "Dirr lösenord",
```suggestion
        "sv-sv": "Ditt lösenord",
```

2022-11-09 09:11 UTC, NoahHakansson commented on app/src/locale/translation.json
> +    "problemes_with_login": {
```suggestion
    "problems_with_login": {
```

2022-11-09 11:08 UTC, NoahHakansson approved these changes

2022-11-09 11:08 UTC, merged